""" constants """
XSAPPNAMEPREFIX = '$XSAPPNAME.'
SYSTEM = 'System'
JOBSCHEDULER = 'JobScheduler'
HDB = 'HDB'
GRANTTYPE_AUTHCODE = 'authorization_code'
GRANTTYPE_PASSWORD = 'password'
GRANTTYPE_CLIENTCREDENTIAL = 'client_credentials'
GRANTTYPE_SAML2BEARER = 'urn:ietf:params:oauth:grant-type:saml2-bearer'
GRANTTYPE_JWT_BEARER = 'urn:ietf:params:oauth:grant-type:jwt-bearer'
KEYCACHE_DEFAULT_CACHE_SIZE = 100
KEYCACHE_DEFAULT_CACHE_ENTRY_EXPIRATION_TIME_IN_MINUTES = 15
HTTP_TIMEOUT_IN_SECONDS = 2
HTTP_RETRY_NUMBER_RETRIES = 3
HTTP_RETRY_ON_ERROR_CODE = [502, 503, 504]
HTTP_RETRY_BACKOFF_FACTOR = 0.5  # retry after 0s, 1s, 2s
