""" constants """
XSAPPNAMEPREFIX = '$XSAPPNAME.'
SYSTEM = 'System'
JOBSCHEDULER = 'JobScheduler'
HDB = 'HDB'
GRANTTYPE_AUTHCODE = 'authorization_code'
GRANTTYPE_PASSWORD = 'password'
GRANTTYPE_CLIENTCREDENTIAL = 'client_credentials'
GRANTTYPE_SAML2BEARER = 'urn:ietf:params:oauth:grant-type:saml2-bearer'
