JWT_SIGNING_PRIVATE_KEY = '-----BEGIN RSA PRIVATE KEY-----\n' \
                          'MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCbVBpnMyO0R8d2' \
                          'Kasc/f/Ziv7XPrzl6I5SXDJtFUb2LzCyA5SH49Qa5AvyGC6UtlZdTkxvAEtMQIAQ' \
                          'xBtxFM1VOiWSriLrsQ/ol6wckgUANsrU2LQq4xw+6LI4u8MqIMQydgbVc/dfdYI1' \
                          '+wJVP1ihT6VYitmv9mwi9CuLyNzOvhGTKdtMGw9oA7KA9SWKmoOulp0w7WaiY0Jt' \
                          '5r+joY+ffwvETDrT0i1+AMaEvp//JWJ3mkXNlBZv72XqYK4nDDSGeE7qC3pG/3w5' \
                          'YO3L0bR+tYA/IR+4hb0H6ZH/a8aHJT0httam8VeLL1FVtuwznfxMKN3kkXZ0m/HL' \
                          'bhp10LihAgMBAAECggEAZVtbI052lPRlztBf7To9kqolozU4NFotTMcGzLGerZSb' \
                          'lP3LFWVwid+Xf/GRq87Tym0GaURq3iYUq1wcgAzP9DZOQEnLVbsjo2YdlEMgakRW' \
                          '1M9XucibLN3RNj4nmzzoafkkenMCz9KxFiJmIlSEtDZxsbZhWHZXl/N22u9GTs0o' \
                          'KQNzroxI+SKxWcfrmJkOx3vL9++47/LY+Rw6dL+hkUxdxMLuhYUcYziNvRfV9o0Y' \
                          'Ag7Pl85xL3N8HkHr5ELL0RKHyk+vKbZ9xhAH50mxTZG8tAj9Ds0v3hQJrTmuyAS3' \
                          'ZJkqkhIJtWHmhLYiKju9ObLXtVgm8wdg8+vq/u1utQKBgQDhEf6Sy0+DhEYTMLN+' \
                          'ioVf/rBXl8QgXbDkEoHMp+FhuYK3CdlD+pgaJq+KUc6RnHb0GeDPBcZkhRlTLxU0' \
                          'HtykDQFa4mcXIJaSKY8WHCF3hJLUnXYgQW+0oufXEDCORuzqgcUbEHnYpjuuzkCj' \
                          'FqjCkH4lNdvW8IJ56rpjBaWyRwKBgQCwrJVWLPPZMuwXHlkM1ytAC+dsq/1cRo3D' \
                          'by766k5u/J6xwlc3bM0LG6pHuXruBxkdKAeAkfmwCc4JSXR4JS3JNmYuQ7wbmDWp' \
                          '20ABv9qFbTIt1rtEkjhV8bmamfe5qZL/0lza2KcQOZGr1wtzV/Vg384gm5oy1FSi' \
                          '0isU+sCJ1wKBgQCFIAuf8Dm75MU+HJROyMhTG2ZaqR4Mtt4mSPwVfUdGcl/qvByS' \
                          'pOrKrQ8vlWvFnPKPN69NRHEwi7mLBlJYXdjMABVJGJk5iMEG+yXzQfhZpUTkFa8F' \
                          'LS9RfPn8r0rJHRKNMuzPMVOg3dJ3du+sh36SdrzmbZD29ZN3YWuVnoV/iQKBgDQM' \
                          '5IJbBAx9gCjffATYb5mS6D+P/DjvYFyvqPurhCgWrPpZ8zAVEeOv5t7yulDeLnv0' \
                          'iyFJ4HIIsXby+SlcarzZFgmTUxweH9FHEvhw+YRNw3bVyJ5PJeHMMY5mxiEg4HoW' \
                          'E9017yJMk6o41NrKkzRTO3tH3IoVHEpL+P1ZUthJAoGALDuPKfHiuXuxxGF4oeyH' \
                          'KFFDIr991nBxUC1tB8Lff5ZStfbzTnjbzCRogsQ/pu1tBaoMQjpHhTnI3hbe/Iwf' \
                          'VffTGJTxapTiEwQuSY2OaSgHtUrz4qurHos+uVTWni8TuXfqkeoc1aIr4D7ulzPN' \
                          'O71jgCLNQW5OZD7MSn21eeU=\n' \
                          '-----END RSA PRIVATE KEY-----'

JWT_SIGNING_PUBLIC_KEY = '-----BEGIN PUBLIC KEY-----\n' \
                         'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAm1QaZzMjtEfHdimrHP3/' \
                         '2Yr+1z685eiOUlwybRVG9i8wsgOUh+PUGuQL8hgulLZWXU5MbwBLTECAEMQbcRTN' \
                         'VTolkq4i67EP6JesHJIFADbK1Ni0KuMcPuiyOLvDKiDEMnYG1XP3X3WCNfsCVT9Y' \
                         'oU+lWIrZr/ZsIvQri8jczr4RkynbTBsPaAOygPUlipqDrpadMO1momNCbea/o6GP' \
                         'n38LxEw609ItfgDGhL6f/yVid5pFzZQWb+9l6mCuJww0hnhO6gt6Rv98OWDty9G0' \
                         'frWAPyEfuIW9B+mR/2vGhyU9IbbWpvFXiy9RVbbsM538TCjd5JF2dJvxy24addC4' \
                         'oQIDAQAB\n' \
                         '-----END PUBLIC KEY-----'

CLIENT_X509_KEY = '-----BEGIN RSA PRIVATE KEY-----\n' \
                  'MIIJKAIBAAKCAgEA7KeODykmA+kxV5HPnmWqX+KzISeM4fgw9z7WQORGiDDTTW6B' \
                  '5czTCZ5u6gCish10jTB8Ewd+VBlEHPBxB3qtm8YDmQoyFA6UP//Ut1uVHE3pW0tL' \
                  '81XalekSmSEwG55BZIB+fO6ET5CJoKCu/Lew2KOw81VO3Pmss7royndB3zobfviu' \
                  'r+nVBm7qWLWjXHfX/USDT89GuyaNN/2iO4cH0o6bs0lrieGN32F3G9lZpgpoikMA' \
                  'E2HQ5HGPSf14a6pg0S2AgEQ+udyX2n2Yb+DHc6aMw3uSO2GHqR6+mSoT2yWZd4Gg' \
                  'vhEo8+KRMKH98Sxmi2edAf5gcYynnBkt4rxZDhhWsRThkLhieSoeNpG3TzpyKfhx' \
                  'FazB4izeNu6NkLO8ujviwhmZUqeK7zcqwGNmuRBy5sEH08f8JxUazVR6mZO5vzyQ' \
                  'hrLDRwjSn3IOjnI4RuvbIub5KZ0AHFAP8ySOljIhQuVLoHmDUy7I07lDpuCbtkOQ' \
                  'ND/FiKDcP4FwKjkeSDaY/qrrl2hF43rAw20O/gGrFk9kQSdv//S/3Oe0pzd+oyFG' \
                  'HF6a9NYZ9eNdHX695Hdot55SkPYuxGfDDiyqa/W+ppVh35W9sk0RKy/l2LAx4hUy' \
                  'DxZJinPz65wI6k2pTyyFtk1RVZCELxHrcyKnBPW84vcGPMD8Mp1pVLKSZIUCAwEA' \
                  'AQKCAgEAkwlcA2FupDlsFdubou/J1r+UyoG3T+MUEVpyZmkuxYmIj/CcNrp3WN+e' \
                  'TDfO3lncw6ifPneGbxwvrMdbgukfGs0CCUFDciDIzabXdIEreSWTWszCyNLL+B6T' \
                  'Fp9/M3m1aYtIi7jqbkEAsdOERbKf50p1NAsJ79QVEKqN3tYQEHEbCl3as6PWXqPl' \
                  'aO6aLGatxUefSqQfb0J5tZMaDGBOZO2EIfX5IfcJXgRBrAT0ZWzMHTOZxXEeCAHi' \
                  'pHcfLc3zT6Q01f0Q+AvuMaudXc3MPrf5d6+8YLatQk++3o09PwjyfEUHKXCiAD4C' \
                  'NbRAgmsy32SmMcnqBEL/FMa0Ms8RiLV+b4xoSt/aNjjHIANps2Kzlx9JdAh9cpJU' \
                  '4vT3w0AjrI5HF7bf9GfeWHQa+txfki/ZhNZJUdi93G6IDccZHA1vfEf6FQmigkNO' \
                  'Fynglk/Y+6AriY9akhyObY/xtT9OrF2kfg3HXXWSLm0tkP/LNkupHP1c+AwBlFhP' \
                  'O9UnbzWZWjA9DRssLJ7PBPmbGlTLShTDjeNDtpDhS8KVtoUP3nxEXlg1PRTJJ1wU' \
                  'r2osqF7DCOKNsw4tDQ4S/AjXNzvWz2HGgYr3iSldbnUeMpnbpn5YO1RXRaAlnEMo' \
                  'ccE+bJYPyRRDtK0kzVO8GUdjs9+Gpa4becHc3LXzH70vOHWzQoECggEBAPrF18CN' \
                  '40fJGgduHcHq39iI8n2nqOIZOU2ancoBjMPL47x6uiBMdNA/qNWoKt9Sfu/ndtgs' \
                  'ti6/cPmxEgS5FZ34jvc5jfGak5J7yxZZLhG3IN+ekQZ/CHzlmDp+jgpQ6sFaoyou' \
                  'axq6CLPGblOXNqVivSovfshyZowWoM8ICYWRJxkGgc+3+gONfFo4oh5/jBK6VZK6' \
                  '+MS83ZHB0HlLmlnJJWkBiboKD8zulnM94m6iC06U+Adb13+gCLwalSgzlcUoXRNl' \
                  'TS13cdLK+9lykQsaNtHfv4UTM817rvLTaPZtm50AMnMkmluvgy+l9LpmoCEjfAf/' \
                  '9x/XtafOZ85sqKUCggEBAPGWX/wz/t438qwhxFyI4Fg3dAFZlwcrCFkHElAXp4Tk' \
                  'hG13K5b/us4A4QGxkSNRysNUTV0iAcQEA6EnM2eaamzSEic8PuAH7XX/WXEERU8J' \
                  'kSu++FL2XRvZpWJUlgCsFXmVuCd3vvYioqjaqUNR9Jk0R2NWk/NICmlMAn6Bhl/X' \
                  'vqUbDTREhZdLjrmTU9+xDlwShCZ+IUIDuSZFBy1BfTN+8Pm/3xlJ7rdgGUNyOMwG' \
                  'P5b4t+bIYbCMazXx95lwwxYTVVl3aaFpxKh988l2g/S+e9ljYvDshtD9jZuiXzFr' \
                  'wILy6/DMcWs6umKIUQnzHoF3Ie6MkJcnToC8joSGJmECggEATFNpLo9BDPlVdct7' \
                  'PSlqxjIwdDRSf7ajrU4RFonQOUvWXeiQvAHpT/UAQz9zBRPL1OMDVhqNvL7B+Q1+' \
                  '6XcX8EPV58NZw56DqgMJthygm/28ALP3eh2yDKmo4qzgOJ2WRhF7Nfx41uKmgWk0' \
                  '7TZKCJ576toX4ZSIR70fZsQQednLJ5/GZN2fN/OZVLCGD3hMvup93zIPQ3okiheO' \
                  'h0yOhyNkwogYTkp/sqUvn5XHVFr3zAwlTcATYCHqZq5Elb7Vp/N4GM4tZlhDiaAE' \
                  'dZOcN9/brZdHaI6GptUtU3UrLk4AHhIQSOFsJdnOuPLvAMj5lfyB5MFwiv2Rqah2' \
                  'CesijQKCAQB1m17ex/Eq/NGGOmn9IiUUzOoMPjDnrGtD681ecCV87EILiBgQSi4G' \
                  'WycuS+L77rVmoYOH8yYo5kteCFdd+C4XC60KrKlvJmzTJJvGCO40q9OgGDeLK6Po' \
                  'CuwYElVzvlI1/kzH6eNsry/AQ7Jis2L/shOOqHcd19Q5rmcIbsWbosuMVL740uK1' \
                  '5HJ2pOIP44G6EMmEc6J9IJLhrnjv7xGkIAfvjRhuly8+1el2jARaTjBmrm3YS3RD' \
                  'HhiTClgeumY+OOszwo4JphO2cppbWPakDpb8HQXtgzeeRdDKEyGETZBKLzfs4ZnV' \
                  'OaHCldndnh0bqYM7PfKlotz0jtZSbXwBAoIBAA9Srb1pqRN31GqQHwnnEQQ5jMcs' \
                  'X71VTzijUfcO9UKOgh1is+EKYehwIgBzic9LELW7tQGqb1Dnq3WCO75XNaks8xt6' \
                  'qU8hljj5ls6aOPt9ecVMiwX1Fbh6YieJB1yWNWtFJdb4+LtpskPVlUMhbTwf5yW5' \
                  'nLEvOFctpxGVKKtS4goXEGYhWB3gMo+vPi/iaF8qW7QAHya0BSzfbR14tNc9My+r' \
                  'bnkl1KK6+HyY+X+i9z9YgQ2+nCccIy/sGDPa5h+KFax7M8mIspCTH2XTjUsTgwWs' \
                  'WyXQxuX7SMGdyVSvtm+VC7Grnt3pXPHZ4DHxTPRIJZhajZ0cQmVWU677JRk=\n' \
                  '-----END RSA PRIVATE KEY-----'

CLIENT_X509_CERTIFICATE = '-----BEGIN CERTIFICATE-----\n' \
                          'MIIFaDCCA1ACCQD0XYB+ksxcszANBgkqhkiG9w0BAQsFADB2MQswCQYDVQQGEwJT' \
                          'RzESMBAGA1UECAwJU2luZ2Fwb3JlMRIwEAYDVQQHDAlTaW5nYXBvcmUxDDAKBgNV' \
                          'BAoMA1NBUDENMAsGA1UEAwwEdGVzdDEiMCAGCSqGSIb3DQEJARYTYWxsZW4ubGl1' \
                          'MDVAc2FwLmNvbTAeFw0yMTA2MDMwNTEzNDNaFw0yMjA2MDMwNTEzNDNaMHYxCzAJ' \
                          'BgNVBAYTAlNHMRIwEAYDVQQIDAlTaW5nYXBvcmUxEjAQBgNVBAcMCVNpbmdhcG9y' \
                          'ZTEMMAoGA1UECgwDU0FQMQ0wCwYDVQQDDAR0ZXN0MSIwIAYJKoZIhvcNAQkBFhNh' \
                          'bGxlbi5saXUwNUBzYXAuY29tMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKC' \
                          'AgEA7KeODykmA+kxV5HPnmWqX+KzISeM4fgw9z7WQORGiDDTTW6B5czTCZ5u6gCi' \
                          'sh10jTB8Ewd+VBlEHPBxB3qtm8YDmQoyFA6UP//Ut1uVHE3pW0tL81XalekSmSEw' \
                          'G55BZIB+fO6ET5CJoKCu/Lew2KOw81VO3Pmss7royndB3zobfviur+nVBm7qWLWj' \
                          'XHfX/USDT89GuyaNN/2iO4cH0o6bs0lrieGN32F3G9lZpgpoikMAE2HQ5HGPSf14' \
                          'a6pg0S2AgEQ+udyX2n2Yb+DHc6aMw3uSO2GHqR6+mSoT2yWZd4GgvhEo8+KRMKH9' \
                          '8Sxmi2edAf5gcYynnBkt4rxZDhhWsRThkLhieSoeNpG3TzpyKfhxFazB4izeNu6N' \
                          'kLO8ujviwhmZUqeK7zcqwGNmuRBy5sEH08f8JxUazVR6mZO5vzyQhrLDRwjSn3IO' \
                          'jnI4RuvbIub5KZ0AHFAP8ySOljIhQuVLoHmDUy7I07lDpuCbtkOQND/FiKDcP4Fw' \
                          'KjkeSDaY/qrrl2hF43rAw20O/gGrFk9kQSdv//S/3Oe0pzd+oyFGHF6a9NYZ9eNd' \
                          'HX695Hdot55SkPYuxGfDDiyqa/W+ppVh35W9sk0RKy/l2LAx4hUyDxZJinPz65wI' \
                          '6k2pTyyFtk1RVZCELxHrcyKnBPW84vcGPMD8Mp1pVLKSZIUCAwEAATANBgkqhkiG' \
                          '9w0BAQsFAAOCAgEAqhOiUG10XMcpJovTSByw0P5XPPduElKOygynGad6vz6r4Ewx' \
                          'vIl21DB26PqQA+WWoKtEvPWQtDPYsv+L/EVoYqOvDeU36utftM+Fv2tUI5IKsPc7' \
                          '4cWA1g+y3ieVM+5EXm5xCgobI07XxxCou6OuAK+wzPzOMmfxtz4w6OxVirjcZBto' \
                          'BrOK9zRQDTBY8hV4ZVEzF/eUPMyAgUt/N+zzikwE9y5sbokTgsoLGAJ72oPm6S3b' \
                          'YF8jRg+nL7rNewm2GXG6Qc/z2hoZvGc9lN4iJYpux2AUNRVTpZpzlsONsgcYxpaP' \
                          'auhzu0wSA85U/CJldK2lmnk5bSYACqXC+K/OSw0j61O4UQyvKjFZidaoEFBu+TTY' \
                          'KGXsCeC6X8mlkKBmpPyuyVi8BA6/fHj7X+cdwAc0kUKtQURimv5L6YA8vxlTtGrg' \
                          'yTiazafTg4+p//nP0cAQ7gV0MsvRbyNRW3HN4xG+yXv2B+5/5MwvNgRZaldBABlu' \
                          'rR0PSGTQlNDxFoPnmdj87gaJfZPpjOLtGgfKaFqbLlcjE1KvBLlRTzfRzN70l85X' \
                          '7ovwBkw8fcwCbFpTbUsEJncZJmdS9XZsr7rvezS3xW5FU0yGsYa8mwI9OU3FGdFE' \
                          'FaH8sgBv0ft/Uey4VJCimkJO/AIZrbXEk2wiy5jLVU8XzPm42D82osnALJA=\n' \
                          '-----END CERTIFICATE-----'
